export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';

export const ADD_SUPERADMIN_PENDING = 'ADD_SUPERADMIN_PENDING';
export const ADD_SUPERADMIN_SUCCESS = 'ADD_SUPERADMIN_SUCCESS';
export const ADD_SUPERADMIN_ERROR = 'ADD_SUPERADMIN_ERROR';

export const EDIT_SUPERADMIN_PENDING = 'EDIT_SUPERADMIN_PENDING';
export const EDIT_SUPERADMIN_SUCCESS = 'EDIT_SUPERADMIN_SUCCESS';
export const EDIT_SUPERADMIN_ERROR = 'EDIT_SUPERADMIN_ERROR';

export const DELETE_SUPERADMIN_PENDING = 'DELETE_SUPERADMIN_PENDING';
export const DELETE_SUPERADMIN_SUCCESS = 'DELETE_SUPERADMIN_SUCCESS';
export const DELETE_SUPERADMIN_ERROR = 'DELETE_SUPERADMIN_ERROR';

export const RESET_PRIMARY_STATES = 'RESET_PRIMARY_STATES';
