export const GET_CLASS_PENDING = 'GET_CLASS_PENDING';
export const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
export const GET_CLASS_ERROR = 'GET_CLASS_ERROR';
export const ADD_CLASS_PENDING = 'ADD_CLASS_PENDING';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const ADD_CLASS_ERROR = 'ADD_CLASS_SUCCESS';
