export const PUT_MEMBERS_PENDING = 'PUT_MEMBERS_PENDING';

export const PUT_MEMBERS_SUCCESS = 'PUT_MEMBERS_SUCCESS';

export const PUT_MEMBERS_ERROR = 'PUT_MEMBERS_ERROR';

export const DELETE_MEMBERS_PENDING = 'DELETE_MEMBERS_PENDING';

export const DELETE_MEMBERS_SUCCESS = 'DELETE_MEMBERS_SUCCESS';

export const DELETE_MEMBERS_ERROR = 'DELETE_MEMBERS_ERROR';
