export const EDIT_SUBSCRIPTIONS_PENDING = 'EDIT_SUBSCRIPTIONS_PENDING';

export const EDIT_SUBSCRIPTIONS_SUCCESS = 'EDIT_SUBSCRIPTIONS_SUCCESS';

export const EDIT_SUBSCRIPTIONS_ERROR = 'EDIT_SUBSCRIPTIONS_ERROR';

export const DELETE_SUBSCRIPTIONS_PENDING = 'DELETE_SUBSCRIPTIONS_PENDING';

export const DELETE_SUBSCRIPTIONS_SUCCESS = 'DELETE_SUBSCRIPTIONS_SUCCESS';

export const DELETE_SUBSCRIPTIONS_ERROR = 'DELETE_SUBSCRIPTIONS_ERROR';

export const RESET_STATE = 'RESET_STATE';
