export const PUT_SUBSCRIPTIONS_PENDING = 'PUT_SUBSCRIPTIONS_PENDING';

export const PUT_SUBSCRIPTIONS_SUCCESS = 'PUT_SUBSCRIPTIONS_SUCCESS';

export const PUT_SUBSCRIPTIONS_ERROR = 'PUT_SUBSCRIPTIONS_ERROR';

export const DELETE_SUBSCRIPTIONS_PENDING = 'DELETE_SUBSCRIPTIONS_PENDING';

export const DELETE_SUBSCRIPTIONS_SUCCESS = 'DELETE_SUBSCRIPTIONS_SUCCESS';

export const DELETE_SUBSCRIPTIONS_ERROR = 'DELETE_SUBSCRIPTIONS_ERROR';

export const RESET_STATE = 'RESET_STATE';
