export const GET_ACTIVITIES_PENDING = 'GET_ACTIVITIES_PENDING';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';

export const ADD_ACTIVITIES_PENDING = 'ADD_ACTIVITIES_PENDING';
export const ADD_ACTIVITIES_SUCCESS = 'ADD_ACTIVITIES_SUCCESS';
export const ADD_ACTIVITIES_ERROR = 'ADD_ACTIVITIES_ERROR';

export const EDIT_ACTIVITIES_PENDING = 'EDIT_ACTIVITIES_PENDING';
export const EDIT_ACTIVITIES_SUCCESS = 'EDIT_ACTIVITIES_SUCCESS';
export const EDIT_ACTIVITIES_ERROR = 'EDIT_ACTIVITIES_ERROR';

export const DELETE_ACTIVITIES_PENDING = 'DELETE_ACTIVITIES_PENDING';
export const DELETE_ACTIVITIES_SUCCESS = 'DELETE_ACTIVITIES_SUCCESS';
export const DELETE_ACTIVITIES_ERROR = 'DELETE_ACTIVITIES_ERROR';

export const RESET_PRIMARY_STATES = 'RESET_PRIMARY_STATES';
export const RESPONSE_ACTIVITIES_MESSAGE = 'RESPONSE_ACTIVITIES_MESSAGE';
