export const LOGIN_ADMIN_PENDING = 'LOGIN_ADMIN_PENDING';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_ERROR = 'LOGIN_ADMIN_ERROR';
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';
